// src/pages/reports/ReportsPage.jsx

import { useState } from 'react';
import {
  Box, Card, CardContent, Typography, Button,
  Grid, Avatar, Divider, Table, TableBody,
  TableCell, TableHead, TableRow, Chip,
  TextField, CircularProgress, Alert
} from '@mui/material';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, PieChart, Pie,
  Cell, Legend, AreaChart, Area
} from 'recharts';
import {
  Assessment, TrendingUp, TrendingDown,
  Download, Receipt, Inventory
} from '@mui/icons-material';
import { useQuery } from '@tanstack/react-query';
import { saleAPI } from '../../services/api';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';

// ── PIE CHART COLORS ──────────────────────────────────
const COLORS = ['#2563eb', '#10b981', '#f59e0b', '#ef4444', '#7c3aed'];

// ── STAT CARD ─────────────────────────────────────────
const StatCard = ({ title, value, icon, color, subtitle }) => (
  <Card>
    <CardContent sx={{ p: 3 }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 1 }}>
        <Box>
          <Typography variant="body2" color="text.secondary" mb={0.5}>
            {title}
          </Typography>
          <Typography variant="h5" fontWeight={700} color={color}>
            {value}
          </Typography>
        </Box>
        <Avatar sx={{ bgcolor: `${color}20`, width: 48, height: 48 }}>
          <Box sx={{ color }}>{icon}</Box>
        </Avatar>
      </Box>
      {subtitle && (
        <Typography variant="caption" color="text.secondary">
          {subtitle}
        </Typography>
      )}
    </CardContent>
  </Card>
);

// ── EXPORT REPORT PDF ─────────────────────────────────
const exportReportPDF = (report) => {
  const doc = new jsPDF();

  // Header
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, 210, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('SmartBiz', 15, 15);
  doc.setFontSize(12);
  doc.text('Sales Report', 15, 25);
  doc.setFontSize(10);
  doc.text(
    `Period: ${report.period.startDate} to ${report.period.endDate}`,
    120, 20
  );

  // Summary
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 15, 50);

  autoTable(doc, {
    startY: 55,
    head: [['Metric', 'Value']],
    body: [
      ['Total Sales',    report.summary.totalSales],
      ['Total Revenue',  `Rs. ${Number(report.summary.totalRevenue).toLocaleString()}`],
      ['Total Expenses', `Rs. ${Number(report.summary.totalExpenses).toLocaleString()}`],
      ['Total Profit',   `Rs. ${Number(report.summary.totalProfit).toLocaleString()}`],
      ['Total Discount', `Rs. ${Number(report.summary.totalDiscount).toLocaleString()}`],
    ],
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // Top Products
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Top Selling Products', 15, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Product', 'Quantity Sold', 'Revenue']],
    body: report.topProducts.map(p => [
      p.name,
      p.quantity,
      `Rs. ${Number(p.revenue).toLocaleString()}`
    ]),
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  });

  // Sales List
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Sales List', 15, doc.lastAutoTable.finalY + 15);

  autoTable(doc, {
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Invoice', 'Customer', 'Amount', 'Payment', 'Date']],
    body: report.sales.map(s => [
      s.invoiceNumber,
      s.customer?.name || 'Walk-in',
      `Rs. ${Number(s.finalAmount).toLocaleString()}`,
      s.paymentMethod?.toUpperCase(),
      new Date(s.createdAt).toLocaleDateString()
    ]),
    headStyles: { fillColor: [37, 99, 235] },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    styles: { fontSize: 9 },
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    'Generated by SmartBiz — AI-Powered Business Management',
    105, 290, { align: 'center' }
  );

  doc.save(`SmartBiz-Report-${report.period.startDate}-to-${report.period.endDate}.pdf`);
  toast.success('Report downloaded! 📊');
};

// ── MAIN REPORTS PAGE ─────────────────────────────────
const ReportsPage = () => {

  // Default to current month
  const today      = new Date();
  const firstDay   = new Date(today.getFullYear(), today.getMonth(), 1);
  const lastDay    = new Date(today.getFullYear(), today.getMonth() + 1, 0);

  const [startDate, setStartDate] = useState(
    firstDay.toISOString().split('T')[0]
  );
  const [endDate, setEndDate] = useState(
    lastDay.toISOString().split('T')[0]
  );
  const [applied, setApplied] = useState({
    startDate: firstDay.toISOString().split('T')[0],
    endDate:   lastDay.toISOString().split('T')[0],
  });

  const { data: report, isLoading, error, refetch } = useQuery({
    queryKey: ['report', applied.startDate, applied.endDate],
    queryFn:  () => saleAPI.report({
      startDate: applied.startDate,
      endDate:   applied.endDate
    }).then(r => r.data.report),
  });

  const handleApply = () => {
    setApplied({ startDate, endDate });
  };

  if (isLoading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', mt: 10 }}>
        <CircularProgress />
      </Box>
    );
  }

  if (error) {
    return <Alert severity="error">Failed to load report.</Alert>;
  }

  return (
    <Box>

      {/* Header */}
      <Box sx={{
        display: 'flex', justifyContent: 'space-between',
        alignItems: 'center', mb: 3
      }}>
        <Box>
          <Typography variant="h4" fontWeight={700}>
            Sales Reports 📊
          </Typography>
          <Typography variant="body2" color="text.secondary" mt={0.5}>
            Analyze your business performance
          </Typography>
        </Box>
        {report && (
          <Button
            variant="contained"
            startIcon={<Download />}
            onClick={() => exportReportPDF(report)}
            sx={{
              background: 'linear-gradient(135deg, #2563eb, #7c3aed)',
              '&:hover': { background: 'linear-gradient(135deg, #1d4ed8, #6d28d9)' }
            }}
          >
            Export PDF
          </Button>
        )}
      </Box>

      {/* Date Filter */}
      <Card sx={{ mb: 3 }}>
        <CardContent sx={{ p: 2, '&:last-child': { pb: 2 } }}>
          <Grid container spacing={2} alignItems="center">
            <Grid item xs={12} sm={4}>
              <TextField
                fullWidth label="Start Date" type="date"
                value={startDate}
                onChange={(e) => setStartDate(e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <TextField
                fullWidth label="End Date" type="date"
                value={endDate}
                onChange={(e) => setEndDate(e.target.value)}
                InputLabelProps={{ shrink: true }}
              />
            </Grid>
            <Grid item xs={12} sm={4}>
              <Button
                fullWidth variant="contained" size="large"
                onClick={handleApply}
                startIcon={<Assessment />}
                sx={{
                  py: 1.8,
                  background: 'linear-gradient(135deg, #2563eb, #7c3aed)',
                  '&:hover': { background: 'linear-gradient(135deg, #1d4ed8, #6d28d9)' }
                }}
              >
                Generate Report
              </Button>
            </Grid>
          </Grid>
        </CardContent>
      </Card>

      {report && (
        <>
          {/* Summary Cards */}
          <Grid container spacing={3} mb={3}>
            <Grid item xs={12} sm={6} md={3}>
              <StatCard
                title="Total Sales"
                value={report.summary.totalSales}
                icon={<Receipt />}
                color="#2563eb"
                subtitle={`${applied.startDate} to ${applied.endDate}`}
              />
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <StatCard
                title="Total Revenue"
                value={`Rs. ${Number(report.summary.totalRevenue).toLocaleString()}`}
                icon={<TrendingUp />}
                color="#10b981"
              />
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <StatCard
                title="Total Expenses"
                value={`Rs. ${Number(report.summary.totalExpenses).toLocaleString()}`}
                icon={<TrendingDown />}
                color="#ef4444"
              />
            </Grid>
            <Grid item xs={12} sm={6} md={3}>
              <StatCard
                title="Net Profit"
                value={`Rs. ${Number(report.summary.totalProfit).toLocaleString()}`}
                icon={<TrendingUp />}
                color={Number(report.summary.totalProfit) >= 0 ? '#10b981' : '#ef4444'}
              />
            </Grid>
          </Grid>

          {/* Charts Row */}
          <Grid container spacing={3} mb={3}>

            {/* Daily Revenue Chart */}
            <Grid item xs={12} md={8}>
              <Card>
                <CardContent sx={{ p: 3 }}>
                  <Typography variant="h6" fontWeight={600} mb={3}>
                    Daily Revenue
                  </Typography>
                  {report.dailyBreakdown.length > 0 ? (
                    <ResponsiveContainer width="100%" height={250}>
                      <AreaChart data={report.dailyBreakdown}>
                        <defs>
                          <linearGradient id="colorRev" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="5%"  stopColor="#2563eb" stopOpacity={0.3} />
                            <stop offset="95%" stopColor="#2563eb" stopOpacity={0} />
                          </linearGradient>
                        </defs>
                        <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                        <XAxis
                          dataKey="date"
                          tick={{ fontSize: 11 }}
                          tickFormatter={(val) => new Date(val).toLocaleDateString('en-GB', {
                            day: '2-digit', month: 'short'
                          })}
                        />
                        <YAxis tick={{ fontSize: 11 }} />
                        <Tooltip
                          formatter={(val) => [`Rs. ${val.toLocaleString()}`, 'Revenue']}
                          labelFormatter={(label) => new Date(label).toLocaleDateString()}
                        />
                        <Area
                          type="monotone" dataKey="revenue"
                          stroke="#2563eb" strokeWidth={2}
                          fill="url(#colorRev)"
                        />
                      </AreaChart>
                    </ResponsiveContainer>
                  ) : (
                    <Box sx={{ textAlign: 'center', py: 5 }}>
                      <Typography color="text.secondary">
                        No sales data for this period
                      </Typography>
                    </Box>
                  )}
                </CardContent>
              </Card>
            </Grid>

            {/* Payment Method Pie Chart */}
            <Grid item xs={12} md={4}>
              <Card sx={{ height: '100%' }}>
                <CardContent sx={{ p: 3 }}>
                  <Typography variant="h6" fontWeight={600} mb={3}>
                    Payment Methods
                  </Typography>
                  {report.paymentBreakdown.length > 0 ? (
                    <ResponsiveContainer width="100%" height={250}>
                      <PieChart>
                        <Pie
                          data={report.paymentBreakdown}
                          dataKey="amount"
                          nameKey="method"
                          cx="50%" cy="50%"
                          outerRadius={80}
                          label={({ method, percent }) =>
                            `${method} ${(percent * 100).toFixed(0)}%`
                          }
                        >
                          {report.paymentBreakdown.map((_, index) => (
                            <Cell
                              key={index}
                              fill={COLORS[index % COLORS.length]}
                            />
                          ))}
                        </Pie>
                        <Tooltip
                          formatter={(val) => [`Rs. ${val.toLocaleString()}`, 'Amount']}
                        />
                      </PieChart>
                    </ResponsiveContainer>
                  ) : (
                    <Box sx={{ textAlign: 'center', py: 5 }}>
                      <Typography color="text.secondary">No data</Typography>
                    </Box>
                  )}
                </CardContent>
              </Card>
            </Grid>
          </Grid>

          {/* Top Products + Sales List */}
          <Grid container spacing={3}>

            {/* Top Products */}
            <Grid item xs={12} md={5}>
              <Card>
                <CardContent sx={{ p: 3 }}>
                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 2 }}>
                    <Inventory color="primary" />
                    <Typography variant="h6" fontWeight={600}>
                      Top Selling Products
                    </Typography>
                  </Box>
                  {report.topProducts.length > 0 ? (
                    <>
                      <ResponsiveContainer width="100%" height={200}>
                        <BarChart data={report.topProducts}>
                          <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
                          <XAxis
                            dataKey="name"
                            tick={{ fontSize: 10 }}
                            tickFormatter={(val) =>
                              val.length > 10 ? val.substring(0, 10) + '...' : val
                            }
                          />
                          <YAxis tick={{ fontSize: 10 }} />
                          <Tooltip
                            formatter={(val) => [`Rs. ${val.toLocaleString()}`, 'Revenue']}
                          />
                          <Bar dataKey="revenue" fill="#2563eb" radius={[4, 4, 0, 0]} />
                        </BarChart>
                      </ResponsiveContainer>
                      <Divider sx={{ my: 2 }} />
                      {report.topProducts.map((product, index) => (
                        <Box
                          key={product.id}
                          sx={{
                            display: 'flex', justifyContent: 'space-between',
                            alignItems: 'center', py: 1,
                            borderBottom: index < report.topProducts.length - 1
                              ? '1px solid #f1f5f9' : 'none'
                          }}
                        >
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Avatar sx={{
                              width: 28, height: 28, fontSize: 12,
                              bgcolor: COLORS[index % COLORS.length]
                            }}>
                              {index + 1}
                            </Avatar>
                            <Typography variant="body2" fontWeight={600}>
                              {product.name}
                            </Typography>
                          </Box>
                          <Box sx={{ textAlign: 'right' }}>
                            <Typography variant="body2" color="primary" fontWeight={600}>
                              Rs. {Number(product.revenue).toLocaleString()}
                            </Typography>
                            <Typography variant="caption" color="text.secondary">
                              {product.quantity} sold
                            </Typography>
                          </Box>
                        </Box>
                      ))}
                    </>
                  ) : (
                    <Box sx={{ textAlign: 'center', py: 3 }}>
                      <Typography color="text.secondary">
                        No products sold in this period
                      </Typography>
                    </Box>
                  )}
                </CardContent>
              </Card>
            </Grid>

            {/* Sales List */}
            <Grid item xs={12} md={7}>
              <Card>
                <CardContent sx={{ p: 3 }}>
                  <Typography variant="h6" fontWeight={600} mb={2}>
                    Sales List ({report.sales.length})
                  </Typography>
                  <Table size="small">
                    <TableHead>
                      <TableRow sx={{ bgcolor: '#f8fafc' }}>
                        <TableCell>Invoice</TableCell>
                        <TableCell>Customer</TableCell>
                        <TableCell align="right">Amount</TableCell>
                        <TableCell>Payment</TableCell>
                        <TableCell>Date</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {report.sales.length === 0 ? (
                        <TableRow>
                          <TableCell colSpan={5} align="center">
                            <Typography
                              variant="body2"
                              color="text.secondary"
                              sx={{ py: 3 }}
                            >
                              No sales in this period
                            </Typography>
                          </TableCell>
                        </TableRow>
                      ) : (
                        report.sales.slice(0, 10).map((sale) => (
                          <TableRow key={sale.id} hover>
                            <TableCell>
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="primary"
                              >
                                {sale.invoiceNumber}
                              </Typography>
                            </TableCell>
                            <TableCell>
                              <Typography variant="body2">
                                {sale.customer?.name || 'Walk-in'}
                              </Typography>
                            </TableCell>
                            <TableCell align="right">
                              <Typography
                                variant="body2"
                                fontWeight={600}
                                color="success.main"
                              >
                                Rs. {Number(sale.finalAmount).toLocaleString()}
                              </Typography>
                            </TableCell>
                            <TableCell>
                              <Chip
                                label={sale.paymentMethod?.toUpperCase()}
                                size="small" variant="outlined"
                                color="primary"
                              />
                            </TableCell>
                            <TableCell>
                              <Typography variant="caption" color="text.secondary">
                                {new Date(sale.createdAt).toLocaleDateString()}
                              </Typography>
                            </TableCell>
                          </TableRow>
                        ))
                      )}
                    </TableBody>
                  </Table>
                </CardContent>
              </Card>
            </Grid>

          </Grid>
        </>
      )}
    </Box>
  );
};

export default ReportsPage;